export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const ACTUALIZAR_USUARIO = 'ACTUALIZAR_USUARIO';
export const CARGANDO = 'CARGANDO';

export const AGREGADO_EXITO = 'AGREGADO_EXITO';
export const AGREGADO_ERROR = 'AGREGADO_ERROR';
export const ELIMINADO_EXITO = 'ELIMINADO_EXITO';
export const ELIMINADO_ERROR = 'ELIMINADO_ERROR';
export const COMPRAR_EXITO = 'COMPRAR_EXITO';
export const COMPRAR_ERROR = 'COMPRAR_ERROR';
export const ACTUALIZAR_EXITO = 'ACTUALIZAR_EXITO';
export const ACTUALIZAR_ERROR = 'ACTUALIZAR_ERROR';
